### ISSUE TITLE
数据问题

### ISSUE THREAD

**Issue by Galaxy-yyyyy** [Oreobird/Face-Occlusion-Detect#2]
下载的数据glass_face（192张）和beard_face（199张）数据，使用os.listdir()列举却比之前多了一倍，即glass_face（384张）和beard_face（398张），多的这部分图像均已“._”+原图像名  命名，请问是什么原因了？

**Comment by Oreobird** [comment]
应该是上传网盘的时候生成的多余隐藏文件，直接删除掉就好，不需要太纠结
